### ISSUE TITLE
Error while Updating to v0.5.1

### ISSUE THREAD

**Issue by naman** [googlesamples/cardboard-unity#59] opened 2015-08-09 13:12 UTC
Cardboard 0.5.1 / Unity 5.1.1f1 

The error has been explained here: http://stackoverflow.com/questions/31902077/how-to-check-my-current-version-of-cardboard-sdk-for-unity-so-that-i-can-update

**Comment by namanspace** [comment] 2015-08-09 16:27
I was able to somehow fix the issue, by creating a new project and importing all Cardboard related files to the old Project.

However, I landed up on this error while building the project.

Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details 

C:/Program Files/Java/jdk1.8.0_51\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/Softwares/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "E:/Softwares/Unity/Editor/Data/BuildTargetTools/AndroidPlayer\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/nano/CodedInputByteBufferNano;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/nano/CodedOutputByteBufferNano$OutOfSpaceException;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/nano/CodedOutputByteBufferNano;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/nano/ExtendableMessageNano;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/nano/Extension$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/nano/Extension$PrimitiveExtension;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/nano/Extension;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/nano/FieldArray;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/nano/FieldData;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
	... 9 more
]
stdout[
processing archive bin\classes.jar...
processing com/unity3d/player/a$1.class...
processing com/unity3d/player/a$2.class...
processing com/unity3d/player/a$a.class...
processing com/unity3d/player/a.class...
processing com/unity3d/player/b$1.class...
processing com/unity3d/player/b$2.class...
processing com/unity3d/player/b.class...
processing com/unity3d/player/c.class...
processing com/unity3d/player/d$1.class...
processing com/unity3d/player/d$2.class...
processing com/unity3d/player/d.class...
processing com/unity3d/player/e.class...
processing com/unity3d/player/f.class...
processing com/unity3d/player/g.class...
processing com/unity3d/player/h.class...
processing com/unity3d/player/i.class...
processing com/unity3d/player/j$1.class...
processing com/unity3d/player/j$2$1$1.class...
processing com/unity3d/player/j$2$1.class...
processing com/unity3d/player/j$2.class...
processing com/unity3d/player/j.class...
processing com/unity3d/player/k$1.class...
processing com/unity3d/player/k.class...
processing com/unity3d/player/l.class...
processing com/unity3d/player/m.class...
processing com/unity3d/player/n$1.class...
processing com/unity3d/player/n.class...
processing com/unity3d/player/NativeLoader.class...
processing com/unity3d/player/o.class...
processing com/unity3d/player/ReflectionHelper$1.class...
processing com/unity3d/player/ReflectionHelper$a.class...
processing com/unity3d/player/ReflectionHelper.class...
processing com/unity3d/player/p.class...
processing com/unity3d/player/q$1.class...
processing com/unity3d/player/q$2.class...
processing com/unity3d/player/q$3.class...
processing com/unity3d/player/q.class...
processing com/unity3d/player/r.class...
processing com/unity3d/player/s.class...
processing com/unity3d/player/UnityPlayer$1.class...
processing com/unity3d/player/UnityPlayer$2.class...
processing com/unity3d/player/UnityPlayer$3.class...
processing com/unity3d/player/UnityPlayer$4.class...
processing com/unity3d/player/UnityPlayer$5.class...
processing com/unity3d/player/UnityPlayer$6.class...
processing com/unity3d/player/UnityPlayer$7.class...
processing com/unity3d/player/UnityPlayer$8.class...
processing com/unity3d/player/UnityPlayer$9.class...
processing com/unity3d/player/UnityPlayer$10.class...
processing com/unity3d/player/UnityPlayer$11.class...
processing com/unity3d/player/UnityPlayer$12$1.class...
processing com/unity3d/player/UnityPlayer$12.class...
processing com/unity3d/player/UnityPlayer$13.class...
processing com/unity3d/player/UnityPlayer$14.class...
processing com/unity3d/player/UnityPlayer$15.class...
processing com/unity3d/player/UnityPlayer$16.class...
processing com/unity3d/player/UnityPlayer$17.class...
processing com/unity3d/player/UnityPlayer$18.class...
processing com/unity3d/player/UnityPlayer$a.class...
processing com/unity3d/player/UnityPlayer$b.class...
processing com/unity3d/player/UnityPlayer$c.class...
processing com/unity3d/player/UnityPlayer.class...
processing com/unity3d/player/UnityPlayerActivity.class...
processing com/unity3d/player/UnityPlayerNativeActivity.class...
processing com/unity3d/player/UnityPlayerProxyActivity.class...
processing com/unity3d/player/t.class...
processing com/unity3d/player/u$1.class...
processing com/unity3d/player/u.class...
processing com/unity3d/player/WWW.class...
processing org/fmod/FMODAudioDevice$a.class...
processing org/fmod/FMODAudioDevice.class...
processing org/fmod/a.class...
processing bitter/jnibridge/JNIBridge$a.class...
processing bitter/jnibridge/JNIBridge.class...
processing archive plugins\.\libprotobuf-java-2.6-nano 1.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/protobuf/
ignored resource com/google/protobuf/nano/
processing com/google/protobuf/nano/CodedInputByteBufferNano.class...
processing com/google/protobuf/nano/CodedOutputByteBufferNano$OutOfSpaceException.class...
processing com/google/protobuf/nano/CodedOutputByteBufferNano.class...
processing com/google/protobuf/nano/ExtendableMessageNano.class...
processing com/google/protobuf/nano/Extension$1.class...
processing com/google/protobuf/nano/Extension$PrimitiveExtension.class...
processing com/google/protobuf/nano/Extension.class...
processing com/google/protobuf/nano/FieldArray.class...
processing com/google/protobuf/nano/FieldData.class...
processing com/google/protobuf/nano/InternalNano.class...
processing com/google/protobuf/nano/InvalidProtocolBufferNanoException.class...
processing com/google/protobuf/nano/MessageNano.class...
processing com/google/protobuf/nano/MessageNanoPrinter.class...
processing com/google/protobuf/nano/UnknownFieldData.class...
processing com/google/protobuf/nano/WireFormatNano.class...
ignored resource com/google/protobuf/nano/android/
processing com/google/protobuf/nano/android/ParcelableExtendableMessageNano.class...
processing com/google/protobuf/nano/android/ParcelableMessageNano.class...
processing com/google/protobuf/nano/android/ParcelableMessageNanoCreator.class...
processing archive plugins\.\libprotobuf-java-2.6-nano.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/protobuf/
ignored resource com/google/protobuf/nano/
processing com/google/protobuf/nano/CodedInputByteBufferNano.class...
processing com/google/protobuf/nano/CodedOutputByteBufferNano$OutOfSpaceException.class...
processing com/google/protobuf/nano/CodedOutputByteBufferNano.class...
processing com/google/protobuf/nano/ExtendableMessageNano.class...
processing com/google/protobuf/nano/Extension$1.class...
processing com/google/protobuf/nano/Extension$PrimitiveExtension.class...
processing com/google/protobuf/nano/Extension.class...
processing com/google/protobuf/nano/FieldArray.class...
processing com/google/protobuf/nano/FieldData.class...
processing com/google/protobuf/nano/InternalNano.class...
processing com/google/protobuf/nano/InvalidProtocolBufferNanoException.class...
processing com/google/protobuf/nano/MessageNano.class...
processing com/google/protobuf/nano/MessageNanoPrinter.class...
processing com/google/protobuf/nano/UnknownFieldData.class...
processing com/google/protobuf/nano/WireFormatNano.class...
ignored resource com/google/protobuf/nano/android/
processing com/google/protobuf/nano/android/ParcelableExtendableMessageNano.class...
processing com/google/protobuf/nano/android/ParcelableMessageNano.class...
processing com/google/protobuf/nano/android/ParcelableMessageNanoCreator.class...
processing archive plugins\.\unitycardboardactivity 1.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/vrtoolkit/
ignored resource com/google/vrtoolkit/cardboard/
ignored resource com/google/vrtoolkit/cardboard/plugins/
ignored resource com/google/vrtoolkit/cardboard/plugins/unity/
processing com/google/vrtoolkit/cardboard/plugins/unity/BuildConfig.class...
processing com/google/vrtoolkit/cardboard/plugins/unity/UnityCardboardActivity$1.class...
processing com/google/vrtoolkit/cardboard/plugins/unity/UnityCardboardActivity$2.class...
processing com/google/vrtoolkit/cardboard/plugins/unity/UnityCardboardActivity.class...
processing archive plugins\.\unitycardboardactivity.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/vrtoolkit/
ignored resource com/google/vrtoolkit/cardboard/
ignored resource com/google/vrtoolkit/cardboard/plugins/
ignored resource com/google/vrtoolkit/cardboard/plugins/unity/
processing com/google/vrtoolkit/cardboard/plugins/unity/BuildConfig.class...
processing com/google/vrtoolkit/cardboard/plugins/unity/UnityCardboardActivity$1.class...
processing com/google/vrtoolkit/cardboard/plugins/unity/UnityCardboardActivity$2.class...
processing com/google/vrtoolkit/cardboard/plugins/unity/UnityCardboardActivity.class...
processing archive plugins\.\unityvractivity 1.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/unity/
processing com/google/unity/GoogleUnityActivity$1.class...
processing com/google/unity/GoogleUnityActivity$2.class...
processing com/google/unity/GoogleUnityActivity$3.class...
processing com/google/unity/GoogleUnityActivity$4.class...
processing com/google/unity/GoogleUnityActivity$5$1.class...
processing com/google/unity/GoogleUnityActivity$5.class...
processing com/google/unity/GoogleUnityActivity$AndroidLifecycleListener.class...
processing com/google/unity/GoogleUnityActivity.class...
ignored resource com/google/vr/
ignored resource com/google/vr/cardboard/
processing com/google/vr/cardboard/ConfigUtils.class...
processing com/google/vr/cardboard/NFCUtils$1.class...
processing com/google/vr/cardboard/NFCUtils.class...
processing com/google/vr/cardboard/UiLayer$1.class...
processing com/google/vr/cardboard/UiLayer$2.class...
processing com/google/vr/cardboard/UiLayer$3.class...
processing com/google/vr/cardboard/UiLayer.class...
processing com/google/vr/cardboard/UiUtils$ConfigureSettingsDialogFragment$1.class...
processing com/google/vr/cardboard/UiUtils$ConfigureSettingsDialogFragment.class...
processing com/google/vr/cardboard/UiUtils$InstallSettingsDialogFragment$1.class...
processing com/google/vr/cardboard/UiUtils$InstallSettingsDialogFragment.class...
processing com/google/vr/cardboard/UiUtils.class...
ignored resource com/google/vr/platform/
ignored resource com/google/vr/platform/unity/
processing com/google/vr/platform/unity/BuildConfig.class...
processing com/google/vr/platform/unity/UnityVrActivityListener$1.class...
processing com/google/vr/platform/unity/UnityVrActivityListener$2.class...
processing com/google/vr/platform/unity/UnityVrActivityListener.class...
processing archive plugins\.\unityvractivity.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/unity/
processing com/google/unity/GoogleUnityActivity$1.class...
processing com/google/unity/GoogleUnityActivity$2$1.class...
processing com/google/unity/GoogleUnityActivity$2.class...
processing com/google/unity/GoogleUnityActivity$AndroidLifecycleListener.class...
processing com/google/unity/GoogleUnityActivity.class...
ignored resource com/google/vr/
ignored resource com/google/vr/gvr/
ignored resource com/google/vr/gvr/platform/
ignored resource com/google/vr/gvr/platform/unity/
processing com/google/vr/gvr/platform/unity/BuildConfig.class...
ignored resource com/google/vr/platform/
ignored resource com/google/vr/platform/unity/
processing com/google/vr/platform/unity/ConfigUtils.class...
processing com/google/vr/platform/unity/NFCUtils$1.class...
processing com/google/vr/platform/unity/NFCUtils.class...
processing com/google/vr/platform/unity/UiUtils$ConfigureSettingsDialogFragment$1.class...
processing com/google/vr/platform/unity/UiUtils$ConfigureSettingsDialogFragment.class...
processing com/google/vr/platform/unity/UiUtils$InstallSettingsDialogFragment$1.class...
processing com/google/vr/platform/unity/UiUtils$InstallSettingsDialogFragment.class...
processing com/google/vr/platform/unity/UiUtils.class...
processing com/google/vr/platform/unity/UnityVrActivityListener$1.class...
processing com/google/vr/platform/unity/UnityVrActivityListener$2.class...
processing com/google/vr/platform/unity/UnityVrActivityListener.class...
processing archive plugins\.\vrtoolkit 1.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/vrtoolkit/
ignored resource com/google/vrtoolkit/cardboard/
processing com/google/vrtoolkit/cardboard/BuildConfig.class...
processing com/google/vrtoolkit/cardboard/CardboardActivity$1.class...
processing com/google/vrtoolkit/cardboard/CardboardActivity.class...
processing com/google/vrtoolkit/cardboard/CardboardDeviceParams$1.class...
processing com/google/vrtoolkit/cardboard/CardboardDeviceParams$VerticalAlignmentType.class...
processing com/google/vrtoolkit/cardboard/CardboardDeviceParams.class...
processing com/google/vrtoolkit/cardboard/CardboardNativeActivity.class...
processing com/google/vrtoolkit/cardboard/CardboardView$1.class...
processing com/google/vrtoolkit/cardboard/CardboardView$Renderer.class...
processing com/google/vrtoolkit/cardboard/CardboardView$StereoRenderer.class...
processing com/google/vrtoolkit/cardboard/CardboardView.class...
processing com/google/vrtoolkit/cardboard/CardboardViewApi.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$1.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$10.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$11.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$12.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$2.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$3.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$4.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$5.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$6.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$7.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$8.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper$9.class...
processing com/google/vrtoolkit/cardboard/CardboardViewJavaImpl$RendererHelper.class...
<message truncated>

**Comment by namanspace** [comment] 2015-08-09 16:54
Repeated the same thing, copied plugins folder from an empty new project. But the procedure of update was still hectic, and lots of changes needed to be done. For a newbie, this might act as a ref.

**Comment by smdol** [comment] 2015-08-09 17:01
Answer added to the StackOverflow page.  Delete the old Cardboard/ and Plugins/ folder (assuming you have no other native code plugins), then import the new version of the SDK.

**Comment by smdol** [comment] 2015-08-26 22:37
Copying the answer from SO here.

https://developers.google.com/cardboard/unity/release-notes

Release notes for v0.5.1 explain: You must remove the Assets/Cardboard/ folder, and all Cardboard-related libraries from the Assets/Plugins folder before upgrading. (If you use no other plugins, just delete the Plugins folder itself.)

This is because a number of files got renamed and moved around for v0.5.1, but Unity's package importer doesn't look for that (it would be very difficult to do). If you just import the new package, you get some files left over from the old version of the package, which leads to the error you see.

**Closed by smdol** 2015-08-26 22:37 UTC
