### ISSUE TITLE
0.5.2 Issue when changing StereoScreenScale at runtime

### ISSUE THREAD

**Issue by MiCkSoftware** [googlesamples/cardboard-unity#100] opened 2015-10-21 15:46 UTC
Hi, 

Issue when changing StereoScreenScale at runtime: screen goes black.

Cheers!

Debug:
```
Releasing render texture that is set as Camera.targetTexture!
UnityEngine.RenderTexture:Release()
Cardboard:set_StereoScreen(RenderTexture) (at Assets/Cardboard/Scripts/Cardboard.cs:336)
Cardboard:set_StereoScreenScale(Single) (at Assets/Cardboard/Scripts/Cardboard.cs:305)
APIGateway:CarboardHighres(Boolean) (at Assets/Whispering Eons/Scripts/Tools/APIGateway.cs:63)
...
```

**Comment by smdol** [comment] 2015-10-21 15:52
As a test, try calling UpdateStereoValues on your StereoController after this change.

**Comment by MiCkSoftware** [comment] 2015-10-21 16:40
Update the code as below and error still pops up.

```
	public static void CarboardHighres(bool b) {
		Cardboard.SDK.StereoScreenScale = b ? 1 : .666666f;
		GameObject.FindObjectOfType<StereoController> ().UpdateStereoValues ();
	}

```

**Comment by smdol** [comment] 2015-10-21 17:10
OK, it was worth a shot.  But I'm not very surprised there's a bug here.  I didn't think of it as a runtime option, so I didn't really test it that way.  But it seems like a worthy use case, so I will try to make it work.

**Comment by MiCkSoftware** [comment] 2015-10-21 17:21
Yes I think it's a great way to mitigate difference in performance from
phones to phones! Thanks!

**Comment by MiCkSoftware** [comment] 2015-10-28 18:27
Reading this http://arstechnica.com/gaming/2015/10/how-dynamic-resolution-scaling-keeps-halo-5-running-so-smoothly/ I think of any easy way to manage FPS. I.e. having 3 render textures of various size and switch constantly to keep a smooth FPS.

**Comment by smdol** [comment] 2015-10-28 19:04
You can actually do this now.  Just create all three RTs up front, and when you want to activate one, assign it to Cardboard.SDK.StereoScreen.  It's possible you may run into the bug you found here, but also possible you won't because this bug might have to do with something you'll avoid by pre-creating the textures.

**Comment by MiCkSoftware** [comment] 2015-10-28 19:37
To my huge things-to-try list added it will be... 😂

**Comment by motorsep** [comment] 2015-10-28 21:12
@smdol Can't you guys make it work automatically? For example, in id Tech 5 engine (RAGE, etc.) once performance drops, renderer automatically kicks in scaled resolution down and when performance increases, it scales it back up. There are a few settings, like minimum threshold (in %%) of scaling, etc.

That would be nice to implement in SDK, so that we wouldn't have to manually do all that.

**Comment by smdol** [comment] 2015-10-28 21:33
Yeah, that's a good feature to have in the SDK, if we can find the right set of scaling steps and thresholds that work for most apps on most phones.  It'll take some experimentation so I can't say for sure when such a feature would land.

**Comment by motorsep** [comment] 2015-10-28 21:45
Actually you would expose scaling steps and thresholds to be set by a game designer. You'd of course have default values, but developers would have to experiment with them to find right values for their games / apps.

**Comment by MiCkSoftware** [comment] 2015-10-29 10:03
+10!

**Comment by smdol** [comment] 2016-01-14 02:58
Quick update:  Although we didn't have a chance to add scaling or steps, the new v0.6 SDK doesn't have the performance issue of v0.5.2, which overcompensated for barrel distortion by making a bigger render texture (too big).

**Comment by MiCkSoftware** [comment] 2016-01-14 20:53
Thanks for the quick update (I was already decreasing size by script). I cross fingers in the hope to see a scaling feature sometimes soon. I'd be happy to do it myself but I have so many things to do...BTW thanks for audio enhancements! 
Cheers!

**Comment by nathanmartz** [comment] 2016-01-22 03:57
Core issue is resolved, requests noted. Closing.

**Closed by nathanmartz** 2016-01-22 03:57 UTC

**Comment by FreezyExp** [comment] 2016-06-28 11:23
It happens again on iOS v0.8, possible issue regression?
