### ISSUE TITLE
Volume buttons stopped working

### ISSUE THREAD

**Issue by DMTSource** [googlesamples/cardboard-unity#40] opened 2015-06-24 15:13 UTC
Since around May 30, the number errors reported by analytics has increase by over 100x. Around this time the volume buttons also stopped working and many users began experiences blank screen or crashes in their reviews. I have created a new empty project with Unity 4.6.6f2 and a fresh download of the official Cardboard Unity plugin and built the Demo scene to my Nexus 5(happens on N6 too) and have seen that the volume buttons do not work. 

Logcat of that attempt:
https://www.dropbox.com/s/zltc7k8enounmyg/CardboardDcemoScene.txt?dl=0

There is also another odd behavior where any touch input code that was working fine before now requires one additional finger to correctly achieve a "held down" state and not just a "tap". I am not sure if that is related to this Cardboard issue.

This has happened in any app using the Cardboard plugin for unity since around May 30. Here is the released app I am referring to when it comes to user errors:
https://play.google.com/store/apps/details?id=com.frag.vrrollercoaster&hl=en

These are the 3 errors that I have received allot from users since the update. I may have done a Cardboard plugin update since May 30 but still get these errors allot:

Exception calling method injectKeypress: UnityEngine.AndroidJavaException: java.lang.NoSuchMethodError: no non-static method 'Lcom/google/vr/platform/unity/UnityVrActivityListener;.injectKeypress(I)V'   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in <filename unknown>:0    at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0    at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJavaObject.Call (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0    at AndroidBaseVRDevice.CallObjectMethod (UnityEngine.AndroidJavaObject jo, System.String name, System.Object[] args) [0x00000] in <filename unknown>:0  

Exception calling method injectKeypress: UnityEngine.AndroidJavaException: java.lang.NoSuchMethodError: no method with name='injectKeypress' signature='(I)V' in class Lcom/google/vr/platform/unity/UnityVrActivityListener;   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in <filename unknown>:0    at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0    at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0    at UnityEngine.AndroidJavaObject.Call (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0    at AndroidBaseVRDevice.CallObjectMethod (UnityEngine.AndroidJavaObject jo, System.String name, System.Object[] args) [0x00000] in <filename unknown>:0  

Object is null when calling method injectSingleTap

**Comment by smdol** [comment] 2015-06-24 16:39
The volume key policy changed, because the NFC tag has been deprecated.  In older versions of the SDK, the NFC tag was used to detect an "in Cardboard" state, and volume keys were disabled because they often get accidentally pushed due to contact with the viewer (plus, being encased in cardboard, they couldn't be reached anyway).  Now, without being able to use the NFC tag, the SDK must assume "in Cardboard" whenever VR mode is enabled, and the volume keys are disabled accordingly.  Your app is specific to a viewing device that doesn't enclose the phone?

The "held down" state has never been supported for the Cardboard Trigger event, because many phones have calibrated compasses, so detecting this with the magnet trigger (for original Cardboard viewers) was not consistent.  So you must be checking for screen taps directly?  And you must have TapIsTrigger set to false?

**Comment by DMTSource** [comment] 2015-06-24 20:51
Volume keys: We are in fact working with a open sided headset(though the app is intended for all Cardboard compliant products and not just our hardware).

Images of our product:
https://goo.gl/eSPdbi

It would be great if it was optional to re enable the volume buttons with a checkbox on the Cardboard script. Otherwise users have to take off the glasses, exit the app, guess their preferred volume, and test it by going back into the app.

Held Down State: In  Unity I am disabling the 'tap is trigger' and am not using the cardboard magnet button in any way. I am only using the native unity touch input script handling such as:
http://docs.unity3d.com/ScriptReference/Input-touches.html

**Comment by smdol** [comment] 2015-06-24 20:55
OK, I think I see where the errors you listed above are coming from, and they are bugs that occur when TapIsTrigger is disabled.  I believe they are new to v0.5, since the underlying native code implementation changed.  Also, the new native code intercepts screen touches and turns them into "tap" events, which is probably why you are seeing the two-finger issue (the first one is absorbed by the native code).

I'm going to put these in as bugs and feature requests internally.  For your short term purposes, would reverting to v0.4.9 work for you?

**Comment by DMTSource** [comment] 2015-06-24 21:14
I link a reversion would help. Is there a place I can download the previous version from? Thank you very much for your efforts!

**Comment by smdol** [comment] 2015-06-24 21:50
Yes, right from this site.  Just select a tag where it currently says "master".

**Comment by VoidZombie** [comment] 2015-08-24 13:02
I need the volume keys to work for my Unity project, since it's some kind of video player. Please, add an option to enable them.

I updated the Cardboard Unity SDK, but I still can't raise the volume when in VR mode.

**Comment by smdol** [comment] 2015-08-24 13:56
This may only be a hacky workaround, but you can adjust the volume if you press the gear icon first.  When done, hit the Cancel button to go back to the game.

**Comment by Smorpheus** [comment] 2015-10-13 21:43
As mentioned above, volume controls are necessary for video players. Users won't know the volume they want until after the video has started playing. We need to have the option to re-enable volume.

**Comment by smdol** [comment] 2015-10-13 23:08
OK.  Can you use the 'tap gear icon, adjust value, hit Cancel' workaround (for now anyway)?  Also, the volume keys are only disabled in VR mode.  If the app exits VR mode, the volume keys work.  (I understand this is ad hoc.)

**Comment by Smorpheus** [comment] 2015-10-14 07:42
I certainly can, but I don't think my clients will be happy with it.  I do notice that Youtube Cardboard implementation on Android also has this problem.  Luckily, i can point to Youtube to show that the SDK just doesn't support it at the moment. I guess this will likely be resolved on the base SDK side and cannot be addressed on the Unity layer?

**Comment by smdol** [comment] 2015-10-14 08:02
Yes.  The motivation for turning the keys off is that when a phone is snug inside a cardboard shell, just holding the cardboard tightly can cause the keys to get activated.  The volume level pop-up is not in stereo, so it really hurts the eyes when it appears. 

What we probably need is a field in the QR code that says whether the viewer is closed or open.  The SDK could just leave the keys be when the viewer is open.

**Comment by VoidZombie** [comment] 2015-10-14 10:54
You can let the developer handle it, as you never know if he's using a
cardboard or another viewer without the button pressing problem. Also, it
would be nice to have two methods to control the volume, like
"raiseVolume(int value)" and the opposite, so I could create two UI buttons
that can be activated by a long stare at it, and can raise or lower the
volume even when inside the viewer, in VR mode.
Il 14/ott/2015 10:02 AM, "smdol" <notifications@github.com> ha scritto:

**Comment by smdol** [comment] 2015-10-14 18:05
The volume key behavior is actually intended for users who get apps from the online stores.  You as a developer don't know what kind of viewer they'll be using.  (At this point, neither does the SDK.)  The SDK was designed when the only viewer model was a fully-enclosing bit of cardboard.  It tends to toggle the volume keys repeatedly -- if you haven't noticed that, that's because the volume key disabling has been doing its job...

As for changing the volume, no need to go through the Cardboard SDK for that.  You have full access to the Android / iOS operating system you are running on.

Anyway, for the general user, I actually see a couple of ways to tackle this problem:
1)  The QR code has a bit that says whether the viewer it describes is an enclosing type or not.
2)  The settings dialog (gear button) sprouts an additional button called "Preferences" that lets the user override various settings, such as volume keys.

**Comment by Smorpheus** [comment] 2015-10-14 20:00
I believe the correct way to handle this is to put the volume controls in 3D Space. This is what Oculus does on the Gear VR. If you gave us hooks to the volume inputs, we could emulate this within our apps.

**Comment by smdol** [comment] 2015-10-14 20:58
Don't know about iOS, but on Android, you can control volume through the AudioManager class:
  http://developer.android.com/reference/android/media/AudioManager.html

Unity provides a proxy class that lets you communicate with Java classes like the above:
  http://docs.unity3d.com/ScriptReference/AndroidJavaProxy.html
See the script BaseAndroidDevice.cs, which has example code that uses this.  So _controlling_ the volume should be doable right now.

The issue you mention about putting the volume overlay in 3D is a good one.  This is one of the things that probably cannot be done so easily on stock Android:  Samsung hacked up their version of Android for Gear, and that may be one of the changes they put in.

**Comment by Smorpheus** [comment] 2015-10-14 23:11
You can control not only native device volume, but also Unity playback volume. The problem is, as it's setup now, I don't believe there's any way for me to actually respond to volume key presses correct? The Cardboard base SDK is capturing and suppressing them at the native level? This is the best I can figure based on device behavior.

**Comment by smdol** [comment] 2015-10-14 23:34
Yes, that's correct.  The keypress happens, and the native SDK code says "if in VR mode, don't pass this key to Unity".  That's the point -- in Cardboard-type viewers, these keys are getting pressed spuriously because the phone is pressed up against the cardboard.  Those keypresses are not intended by the user, they cause the not-in-stereo volume bar to appear, which hurts the user's eyes, etc.  But if we had an augmented QR code that tells the SDK "hey, this viewer doesn't enclose the phone", then the SDK would not stop them from passing through. 

But if you want to add floating buttons in virtual space that adjust volume, you don't need the keypresses, right?

**Comment by Smorpheus** [comment] 2015-10-14 23:45
First, thanks for all the replies, I'm sure this thread will help others when dealing with clients who are giving us a hard time for not having volume controls.

I could add it to the pause menu for sure. It's a bit awkward for an app that primarily plays back videos, though. We could also have a "sound adjustment" scene before the actual Cardboard portion launches.

However if the Cardboard SDK passed through an event I could respond to when the volume button press occurs, that would be ideal. I could respond to the event however I like. I could either ignore it, as you've locked in the current version of the SDK, or I could handle it gracefully with a 3D volume control. Also, why is the SDK not just adjusting the volume via AudioManager while suppressing the 2D overlay? Wouldn't that be a better behavior?

**Comment by smdol** [comment] 2015-10-15 00:49
Well, like I said, when the phone is in a Cardboard, most of the volume key presses are accidental, from the cardboard squeezing against the side of the phone.  Also, there's no way to suppress the 2D overlay (at least since Android 5.0 -- got rid of "silent" mode).

**Comment by smdol** [comment] 2016-01-22 06:04
Volume controls are no longer disabled in Cardboard as of v0.5.2, the injectKeyPress error is also fixed in the same release.

**Closed by smdol** 2016-01-22 06:04 UTC
