### ISSUE TITLE
Android Cardboard app crashes on tilt

### ISSUE THREAD

**Issue by ghost** [googlesamples/cardboard-unity#117] opened 2015-11-05 13:19 UTC
See my stackoverflow post for details: http://stackoverflow.com/questions/33544158/cardboard-demo-crashes-on-android-on-tilt?noredirect=1#comment54869379_33544158

In short, I've made a new Cardboard project (in Unity 5.2.1f1) with some minimal changes and the app crashes when I tilt the phone. Not every time, but 90% of the time maybe.

**Comment by smdol** [comment] 2015-11-05 14:47
The Application.LoadLevel() function causes the current Cardboard object to get destroyed.  I'm guessing that process races with your code's return from the event callback.  

To see if that is so, try writing your code not as an event handler, but as a simple if-statement in an Update function:

    void Update() {
        if (Cardboard.SDK.Tilted)
            Application.LoadLevel("foo");
    }

**Comment by tework2015** [comment] 2015-11-05 15:26
I tried it, but it still crashes... It does, however, *seem* to have something to do with loading a new scene while doing it. When all I do is changing the color of the cube that I attached the script to, it works without problems. Any other ideas/workarounds?

Also, can I suggest one thing for the Cardboard SDK? To make it possible to adjust the sensitivity for when a tilt should be registered. Like an "angle threshold" or something. The reason is that I feel that it's sometimes tricky to trigger it :)

**Comment by tework2015** [comment] 2015-11-09 09:22
I've now tried to make minimal test projects using both cardboard sdk 5.1 and 5.2.
5.2 always crashes when I try to change scene by tilting. 5.1 seem to work without problems; hasn't crashed for me yet.

**Comment by smdol** [comment] 2015-11-09 15:06
Could you share that test project here by a Drive or Dropbox link?

**Comment by tework2015** [comment] 2015-11-10 07:56
here you go:
https://onedrive.live.com/redir?resid=D35CC4807B4AA70E!113&authkey=!AEJ4S1VdxUIx_Ig&ithint=file%2czip

**Comment by smdol** [comment] 2015-11-10 22:03
Reproduced.  Found the following message in the logcat:

    W Unity   : Cardboard SDK object should be a singleton.

That indicates that two Cardboards exist somehow in the second scene.  That's a definite no-no (imposed by the native code layer).  Removing the 2nd copy of the Cardboard script in scene2 makes the crash go away.  (Side note:  I just checked the web site, and this singleton issue doesn't seem to be called out.  I thought it was.)

**Comment by tework2015** [comment] 2015-11-11 08:55
Nice! Although I'm not sure how to do this exactly.

**Comment by smdol** [comment] 2015-11-11 16:32
Change the line

    if (Cardboard.SDK.Tilted) ...

To

   if (Cardboard.SDK.Tilted || Input.GetKeyUp(KeyCode.P)) ...

Now play the first scene in the editor and hit the 'P' key to simulate a tilt.  (You can use some other KeyCode if you want...)

I did that yesterday and saw that same warning message about singletons in the Unity console.  That's when I noticed the 2nd game object with its own Cardboard script that was in scene2.  

Try this too, and see if you also still get that warning.

**Comment by tework2015** [comment] 2015-11-12 10:31
Today's my last day at work, so I won't be able to test this anymore, sorry...
Big thanks for your help! Good luck.

**Comment by Vectorizing** [comment] 2016-01-06 23:23
This is the same issue as https://github.com/googlesamples/cardboard-unity/issues/125

The singleton is because there is a 2nd cardboard object somewhere in the scene. I have noticed if you disable the CardboardMain gameobject and leave the Cardboard.cs script enabled, if you click on CardboardMain it will create another instance of the Cardboard in the scene.. not sure why this happens.

Like the other issue, this one occurs because the device is tiled. If you enable/disable the gameobject, try to load a scene, or try to quit the app and the device has been tiled or moved rapidly, the app will crash with a SIGSEGV 11 error. If you move slowly and don't tilt it a lot it seems to be fine.

For some reason rapid movement and tilt is causing the cardboard sdk to mess up somewhere. I tried commenting out the OnTilt() function on the Cardboard.cs script and it still crashed.

if (Tilted && OnTilt != null)
{
     //OnTilt();
}

Trying to find a workaround to this so my apps quit crashing for users.. but I'm not having any luck.

**Comment by smdol** [comment] 2016-01-07 02:53
Yeah, the crash is happening down in the native code layer.  Not much you can do in C# with the current release.  It is going to be fixed in the next release.  Same with the other problem where a Cardboard is instantiated.  (This comes from the editor script for Cardboard referencing "Cardboard.SDK" on one line rather than "cardboard".)

**Comment by smdol** [comment] 2016-01-14 02:50
New v0.6 release of the SDK fixes tilt crash.  Unfortunately, it was more of a bypass, in that we had to disable the tilt detection in the native library altogether.  This means that Tilted and OnTilt are orphans at the moment -- they will not report anything.  A similar detection can be built in C# using Input.accel or Unity's DeviceOrientation support.

**Closed** 2016-01-22 00:21 UTC
