### ISSUE TITLE
Crash on Application.Quit after tilting

### ISSUE THREAD

**Issue by Euan-Climax** [googlesamples/cardboard-unity#125] opened 2015-12-11 12:31 UTC
If I call Application.Quit() any time after having tilted (Cardboard.SDK.Tilted was true), then the app will crash with dialog "Unfortunately, -app- has stopped.".
If I haven't ever tilted, the app will quit without error.

Occurs in both our main project and an empty project consisting of just a camera.

Cardboard SDK v0.5.2
Unity 4.6.3p3
Android 4.4.2

**Comment by justinwasilenko** [comment] 2015-12-11 15:45
Can confirm this, always wandered what caused this crash in my app, just tested it and found it to be the same.

Using Cardboard SDK 0.5.2 as well and Unity 5.2.3, Android 5.

**Comment by smdol** [comment] 2015-12-11 16:15
The most likely cause is referring to "Cardboard.SDK" after the Cardboard object has been destroyed.  This can happen when unregistering the OnTilt event handler, for instance.  This is a definite bug that will be fixed in an upcoming release.  If this sounds like what is happening to you, avoid using the guilty Cardboard events for now.  If it is not the cause, then... more investigation is needed.  Is it easy to massage a test case?

**Comment by Euan-Climax** [comment] 2015-12-14 10:36
Simple test case:
Create a new 3D project, add Cardoard to the camera, and add a script with the following update function:
```
void Update () {
        if (Time.realtimeSinceStartup > 10)
        {
            Application.Quit();
        }
}
```
Perform a tilt before it quits and observe crash.

**Comment by smdol** [comment] 2015-12-15 07:47
Reproduced.  Interestingly you have to tilt the phone to the right.  This means it is not just an orientation change, but something to do with the OnTilt gesture specifically.

**Comment by MiCkSoftware** [comment] 2015-12-15 10:53
Just to note: I wonder it there could be some bad interaction with the
gesture that triggers experience exiting in the official cardboard app...

**Comment by Vectorizing** [comment] 2015-12-19 22:58
Happens to me as well. I can use my app and if I don't tilt and just look around slowly it will work but if I tilt the cardboard and move it around fast then disable and re-enable it, the app will crash. I have tried instantiating the CardboardMain prefab and Destroying it each time but I don't think that is the best practice. Also I removed my quit button because application.quit would crash the app as well..

Any updates on this issue? 

Thanks for your time.

**Comment by smdol** [comment] 2015-12-19 23:31
Yes, the update is that the problem is down in the native code that monitors the sensors.  It has to be fixed there for an upcoming release.  It is being worked on.

**Comment by Vectorizing** [comment] 2015-12-19 23:33
Thank you sir, appreciate the update! :)

**Comment by samurai926** [comment] 2015-12-25 15:17
Looking forward to this fix!

**Comment by smdol** [comment] 2016-01-14 02:47
v0.6 is out, and fixes the problem -- or rather, bypasses it.  The downside is that we had to stop reporting the "tilt" event.  If you are using Cardboard.SDK.Tilted or OnTilt, they will no longer report anything.  If you need this functionality, you can use Input.accel to implement it in C#.

**Closed** 2016-01-22 00:18 UTC
