### ISSUE TITLE
Reopening Cardboard app results in black screen

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#70] opened 2015-08-26 16:37 UTC
Since "go back" button (to the right from Home button) on the phone does nothing when running Unity app made with default SDK example, I use Home button to get out of the app. When I open my app again, all I have is black screen (left and right eyes, but pitch black). Other Cardboard apps (made with Unity) don't seem to have such issue.

**Comment by smdol** [comment] 2015-08-26 21:32
That doesn't happen for me.  First thing to do is check the logcat for any error messages.  

You mentioned in another issue that you use Unity 5.1, which would rule out some of the Unity bugs in 5.0 that they fixed which affected Cardboard apps this way.

**Comment by motorsep** [comment] 2015-08-26 21:37
@smdol Where do I find logcat ?

**Comment by smdol** [comment] 2015-08-26 22:08
The logcat is where Android apps dump all their logging info on the phone.  You can print it out on your computer using the "adb" command.  That's a command-line / console tool included in the Android SDK, in the platform-tools/ subdirectory.  

If you don't have a platform-tools subdirectory, you have to open the Android SDK manager and install the "Android SDK Platform-tools" package to get it.  To do *that*, run the "android" command in the SDK's tools/ directory and use the GUI that appears to select and install it.  

Once you have it, and your phone is connected by USB, open a console window and run the "adb logcat" command.

**Comment by noemis84** [comment] 2015-09-01 14:29
hey smdol, I can confirm strange black screen behavior on android (different devices) after resume. I use unity 5.1.3f and the cardboard sdk 0.5.1

what I also noticed, that it works in the scene, where the cardboard is created, but not after loading another scene... here's a stepe by step description:

1. start app
2. start vr mode in the app (instantiate cardboard prefab) and load first scene, works perfect
3. "exit" via home button and resume works
4. now loading next scene (level), cardboard object is not destroyed, it's child of a dontDestoryOnLoad object
5. but now pressing home and resume show just black screen... i can still hear some raycast functions, but no visible output

logcat shows no errors :(

I'm still trying to figure out the problem, but maybe you have another hint what to try.

I can also send an apk if you want.

beste regards
Simeon

**Comment by noemis84** [comment] 2015-09-01 16:15
UPDATE: I think a found the problem / "solution": there is a problem if "Multithreaded Rendering" is enabled in PlayerSettings.

My testsetup (if important):

I created a new project, imported the sdk and created 3 scenes:

1st scene contains just an empty object with a script, which does the following:
- DontDestroy yourself onLoad and StartCoroutine ;)
   - wait 5seconds and load scene 2
   - create prefab "CardboardMain"
   - wait 5seconds and load scene 3

2nd scene = skybox + cube + textmesh
2rd scene = skybox + sphere + textmesh

Result after launch on Android:
With "Multithreaded Rendering" enabled: 3rd scene is black after resume / 2nd has a render/shading bug
With "Multithreaded Rendering" disabled: 1st - 3rd scene is fine after resume

**Comment by motorsep** [comment] 2015-09-01 16:19
@noemis84 Could you please file a bug report with Unity (I am not even sure they have such thing o.O) ?

**Comment by smdol** [comment] 2015-09-01 16:27
Yep, the Cardboard SDK has never worked with multithreaded rendering in Unity.  It's in the release notes here:  
    https://developers.google.com/cardboard/unity/release-notes#known_issues

**Comment by motorsep** [comment] 2015-09-01 16:30
Ohh. Will it work with multithreaded rendering any time soon? (I think it's kinda critical to utilize multi-CPU / GPU architecture for maximum performance)

**Comment by smdol** [comment] 2015-09-01 16:37
I really hope so, but I think it's Unity's issue with native rendering plugins.

**Comment by noemis84** [comment] 2015-09-01 16:59
Ahhh.. thank you for the fast response/tip. Normally I've the "known issues" on my mind, but since most thinks work like a charme after first import I forgot them ;)

The only thing I had to changed in the original cardboard.cs script is under OnLevelWasLoaded() there is a device.Reset() - which recenters the orientation

In my case that doesn't make sense, cause the orientation between different scenes may not change... maybe this could be an option in general settings or so?

**Comment by smdol** [comment] 2015-09-01 17:18
Actually, all that Reset() currently does (by default) is call Recenter().  It might be better to remove that and let you (the app developer) decide when recentering is appropriate, and call Cardboard.Recenter() when you want.  Reset() is really meant to tell the device class to clear any internal state that should not survive a level load.

**Comment by motorsep** [comment] 2015-09-09 13:20
Has anyone already tested Unity 5.2 with Cardboard on the subject of multithreaded rendering working ?

**Comment by 2600th** [comment] 2015-09-16 17:27
Still having issue with 5.2. When I plug my device into the viewer the NFC causes cardbord app to launch and when I go back into my application (multithreading enabled) there's only black screen.

**Comment by smdol** [comment] 2015-10-14 04:38
The new v0.5.2 seems to not crash with multithreading enabled, so that's nice.  The gyro seems more jittery though, which is not so nice.  Still trying to figure that out.  Closing this bug as it was originally about the "multithreading black screen".

**Closed by smdol** 2015-10-14 04:38 UTC
