### ISSUE TITLE
Size problem on Cardboard surface with HTC One X

### ISSUE THREAD

**Issue by qwarnant** [googlesamples/cardboard-unity#13] opened 2015-01-26 09:34 UTC
Hello,

I've experienced a problem with the cardboard surface on HTC devices. The stereo views on the HTC phone has a very small dimension compared with the other phones like Sony devices. I've tried various HTC One X devices with different android version (4.4.4 and 4.2) and the result is the same, the view on the HTC seems to not be in "full screen" mode. 

This is the "normal" view size on my phone (Sony) in my app : 
![Normal screen](https://lh6.ggpht.com/qqjJ-BUg36tdVYV3x8temcIhFZcSuSn0Ukz_P99eqBYUL5T0b8v0QPfS-CXcHJoVONg=h900-rw)

This is the "small" view size on the HTC phone in my app :
![Small screen](http://o03.imgup.net/Screenshot9c59.png)

Any idea to fix this problem ? Thank you.

**Comment by smdol** [comment] 2015-01-29 05:20
Are you able to get into immersive mode with other apps?  If not, there is a possible fix here:

http://appslova.com/how-to-enable-immersive-mode-on-android-without-root/

**Comment by qwarnant** [comment] 2015-01-29 16:32
Hello,
I've tested to put manually one of the HTC devices in immersive mode, but the result on the view is the same. With other cardboard apps without the unity3d plugin, I don't have this problem, each side of the view takes correctly the full available space on the screen. Maybe a problem with the computation of the render view size on HTC GPU devices with the plugin ?

**Comment by smdol** [comment] 2015-01-30 01:12
It looks like the HTC screenshot shows the top bar, so it did not go into immersive mode.  Also, I don't see the settings gear icon.  I know there is a bug in the Cardboard Unity plugin that affects how it interacts with Android -- the gyro and accelerometer are not accessible in Input -- and I wonder if this is also an effect of that bug.  If that is the problem, then when the bug is fixed, this problem will be fixed too.  One way to test this:  You mentioned other cardboard apps without unity3d.  What about other unity3d apps without the cardboard plugin?  If they can make the screen immersive mode, then it is likely to be that bug.  

One other thing to look for:  Does adb logcat show any error messages?

**Comment by qwarnant** [comment] 2015-01-30 16:35
Hi,
The top bar on the phone appears when we takes a screenshot (it's a custom rom device), it's a normal behaviour of the device. For the presence of the gear icon, it's normal, i've unchecked this feature of plugin in the unity editor. So, we have made several other tests : 
- We have tested if other "simple" unity3d apps without any cardboard or vr plugins : the app is running normally with full available screen.
- We have launched the official cardboard app (i don't know which SDK this app is using), the problem is the same th
! [Screenshot official cardboard app] (http://z18.imgup.net/Screenshotbaf7.png)
- We have checked the adb logs and there were no error messages.

**Comment by smdol** [comment] 2015-01-30 20:58
Based on your latest information, it looks like the HTC One X may be reporting an incorrect dpi.  I've heard of some other models that also have this problem.  The dpi is used to calculate the size of the screen in mm.  The SDK needs to know this in order to compute the correct projection matrix.  It doesn't seem to matter whether GetMetrics() is used, or GetRealMetrics() -- some phones return the wrong dpi for one of those calls or the other.  The result is the SDK thinks the screen is smaller than it is, and the smaller image is rendered like you see it:  centered horizontally and at the bottom edge of the phone.

**Comment by qwarnant** [comment] 2015-01-30 21:39
Okay,

Thank you very much for your good explanation of the problem. One more weird thing happened, when we tried to play [this app](https://play.google.com/store/apps/details?id=com.limecolor.unity.card_board_for_unity.debris) (present on cardboard play store) : the stereo view works perfectly. However, in the description of the app, the developer says "This is Card board unity3d plugin sample game". Maybe he provided a bug fix in the unity3d plugin...

**Comment by smdol** [comment] 2015-01-30 21:44
I know that the underlying Java SDK switched from one of the two calls GetMetrics and GetRealMetrics at some point.  The hope was this would fix the dpi issue, but it was then found that it only made a different set of phones report a problem.  Likely he has an older version of the Cardboard SDK that uses the other metrics function from your version, and that one happens to give the correct answer on your phone!  :(

**Comment by qwarnant** [comment] 2015-02-01 08:02
Ok ! Thank you for explanation ! Therefore, this is an issue than can not be fixed by the Cardboard team. Should I close this thread ?

**Comment by smdol** [comment] 2015-02-03 05:14
I guess the thread should be closed.  Regardless of how the issue is solved, it is not really a bug in the Cardboard-Unity SDK itself.

**Closed** 2015-02-03 07:42 UTC
