### ISSUE TITLE
LG G3 Gyro Issues(Cardboard 0.6)

### ISSUE THREAD

**Issue by Oshroth** [googlesamples/cardboard-unity#145] opened 2016-01-19 05:54 UTC
I'm having an issue with my LG G3 where the Head Pose resets back to center frequently and randomly. It also occurs in the Cardboard Demo Project.
I'm using Cardboard 0.6 and Unity 5.3.1p2

The problem doesn't occur on any of my other dev phones or tablets that I've tested so far:
Nexus 7, Nexus 9, Samsung S5, Samsung S4

**Comment by smdol** [comment] 2016-01-19 06:36
Duplicate of #120.

**Closed by smdol** 2016-01-19 06:36 UTC
